version: 2
updates:
  # ESP-IDF component dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"

  # Web interface npm dependencies
  - package-ecosystem: "npm"
    directory: "/web-interface"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "web-interface"
    commit-message:
      prefix: "chore(deps)"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      next:
        patterns:
          - "next*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Root npm dependencies (commitlint, husky, etc.)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "tooling"
    commit-message:
      prefix: "chore(deps)"
